# inpackage: True
with-expecter: True
outpkg: "{{.PackageName}}_mocks"
filename: "{{.InterfaceName | firstLower}}_mock.go"
dir: "mocks/{{.InterfaceDirRelative}}"
# dir: "{{.InterfaceDir}}"
packages:
  github.com/lambda-feedback/shimmy/internal/execution/worker:
    config:
      outpkg: "{{.PackageName}}"
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Worker:
  github.com/lambda-feedback/shimmy/internal/execution/supervisor:
    config:
      outpkg: "{{.PackageName}}"
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Adapter:
      Supervisor:
  github.com/lambda-feedback/shimmy/internal/execution/dispatcher:
    config:
      outpkg: "{{.PackageName}}"
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Dispatcher:
# testonly: True