// Code generated by mockery v2.43.0. DO NOT EDIT.

package dispatcher

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockDispatcher is an autogenerated mock type for the Dispatcher type
type MockDispatcher[I interface{}, O interface{}] struct {
	mock.Mock
}

type MockDispatcher_Expecter[I interface{}, O interface{}] struct {
	mock *mock.Mock
}

func (_m *MockDispatcher[I, O]) EXPECT() *MockDispatcher_Expecter[I, O] {
	return &MockDispatcher_Expecter[I, O]{mock: &_m.Mock}
}

// Send provides a mock function with given fields: _a0, _a1
func (_m *MockDispatcher[I, O]) Send(_a0 context.Context, _a1 I) (O, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 O
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, I) (O, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(context.Context, I) O); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(O)
	}

	if rf, ok := ret.Get(1).(func(context.Context, I) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockDispatcher_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockDispatcher_Send_Call[I interface{}, O interface{}] struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - _a0 context.Context
//   - _a1 I
func (_e *MockDispatcher_Expecter[I, O]) Send(_a0 interface{}, _a1 interface{}) *MockDispatcher_Send_Call[I, O] {
	return &MockDispatcher_Send_Call[I, O]{Call: _e.mock.On("Send", _a0, _a1)}
}

func (_c *MockDispatcher_Send_Call[I, O]) Run(run func(_a0 context.Context, _a1 I)) *MockDispatcher_Send_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(I))
	})
	return _c
}

func (_c *MockDispatcher_Send_Call[I, O]) Return(_a0 O, _a1 error) *MockDispatcher_Send_Call[I, O] {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockDispatcher_Send_Call[I, O]) RunAndReturn(run func(context.Context, I) (O, error)) *MockDispatcher_Send_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: _a0
func (_m *MockDispatcher[I, O]) Shutdown(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDispatcher_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockDispatcher_Shutdown_Call[I interface{}, O interface{}] struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDispatcher_Expecter[I, O]) Shutdown(_a0 interface{}) *MockDispatcher_Shutdown_Call[I, O] {
	return &MockDispatcher_Shutdown_Call[I, O]{Call: _e.mock.On("Shutdown", _a0)}
}

func (_c *MockDispatcher_Shutdown_Call[I, O]) Run(run func(_a0 context.Context)) *MockDispatcher_Shutdown_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDispatcher_Shutdown_Call[I, O]) Return(_a0 error) *MockDispatcher_Shutdown_Call[I, O] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDispatcher_Shutdown_Call[I, O]) RunAndReturn(run func(context.Context) error) *MockDispatcher_Shutdown_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: _a0
func (_m *MockDispatcher[I, O]) Start(_a0 context.Context) error {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockDispatcher_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockDispatcher_Start_Call[I interface{}, O interface{}] struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - _a0 context.Context
func (_e *MockDispatcher_Expecter[I, O]) Start(_a0 interface{}) *MockDispatcher_Start_Call[I, O] {
	return &MockDispatcher_Start_Call[I, O]{Call: _e.mock.On("Start", _a0)}
}

func (_c *MockDispatcher_Start_Call[I, O]) Run(run func(_a0 context.Context)) *MockDispatcher_Start_Call[I, O] {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockDispatcher_Start_Call[I, O]) Return(_a0 error) *MockDispatcher_Start_Call[I, O] {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockDispatcher_Start_Call[I, O]) RunAndReturn(run func(context.Context) error) *MockDispatcher_Start_Call[I, O] {
	_c.Call.Return(run)
	return _c
}

// NewMockDispatcher creates a new instance of MockDispatcher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDispatcher[I interface{}, O interface{}](t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDispatcher[I, O] {
	mock := &MockDispatcher[I, O]{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
