// Code generated by mockery v2.43.0. DO NOT EDIT.

package supervisor

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// MockSupervisor is an autogenerated mock type for the Supervisor type
type MockSupervisor struct {
	mock.Mock
}

type MockSupervisor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSupervisor) EXPECT() *MockSupervisor_Expecter {
	return &MockSupervisor_Expecter{mock: &_m.Mock}
}

// Send provides a mock function with given fields: ctx, result, method, data
func (_m *MockSupervisor) Send(ctx context.Context, result interface{}, method string, data map[string]interface{}) (ReleaseFunc, error) {
	ret := _m.Called(ctx, result, method, data)

	if len(ret) == 0 {
		panic("no return value specified for Send")
	}

	var r0 ReleaseFunc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, map[string]interface{}) (ReleaseFunc, error)); ok {
		return rf(ctx, result, method, data)
	}
	if rf, ok := ret.Get(0).(func(context.Context, interface{}, string, map[string]interface{}) ReleaseFunc); ok {
		r0 = rf(ctx, result, method, data)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(ReleaseFunc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, interface{}, string, map[string]interface{}) error); ok {
		r1 = rf(ctx, result, method, data)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupervisor_Send_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Send'
type MockSupervisor_Send_Call struct {
	*mock.Call
}

// Send is a helper method to define mock.On call
//   - ctx context.Context
//   - result interface{}
//   - method string
//   - data map[string]interface{}
func (_e *MockSupervisor_Expecter) Send(ctx interface{}, result interface{}, method interface{}, data interface{}) *MockSupervisor_Send_Call {
	return &MockSupervisor_Send_Call{Call: _e.mock.On("Send", ctx, result, method, data)}
}

func (_c *MockSupervisor_Send_Call) Run(run func(ctx context.Context, result interface{}, method string, data map[string]interface{})) *MockSupervisor_Send_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(interface{}), args[2].(string), args[3].(map[string]interface{}))
	})
	return _c
}

func (_c *MockSupervisor_Send_Call) Return(_a0 ReleaseFunc, _a1 error) *MockSupervisor_Send_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupervisor_Send_Call) RunAndReturn(run func(context.Context, interface{}, string, map[string]interface{}) (ReleaseFunc, error)) *MockSupervisor_Send_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function with given fields: ctx
func (_m *MockSupervisor) Shutdown(ctx context.Context) (WaitFunc, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 WaitFunc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (WaitFunc, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) WaitFunc); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(WaitFunc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupervisor_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockSupervisor_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSupervisor_Expecter) Shutdown(ctx interface{}) *MockSupervisor_Shutdown_Call {
	return &MockSupervisor_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockSupervisor_Shutdown_Call) Run(run func(ctx context.Context)) *MockSupervisor_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSupervisor_Shutdown_Call) Return(_a0 WaitFunc, _a1 error) *MockSupervisor_Shutdown_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupervisor_Shutdown_Call) RunAndReturn(run func(context.Context) (WaitFunc, error)) *MockSupervisor_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Start provides a mock function with given fields: ctx
func (_m *MockSupervisor) Start(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Start")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSupervisor_Start_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Start'
type MockSupervisor_Start_Call struct {
	*mock.Call
}

// Start is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSupervisor_Expecter) Start(ctx interface{}) *MockSupervisor_Start_Call {
	return &MockSupervisor_Start_Call{Call: _e.mock.On("Start", ctx)}
}

func (_c *MockSupervisor_Start_Call) Run(run func(ctx context.Context)) *MockSupervisor_Start_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSupervisor_Start_Call) Return(_a0 error) *MockSupervisor_Start_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSupervisor_Start_Call) RunAndReturn(run func(context.Context) error) *MockSupervisor_Start_Call {
	_c.Call.Return(run)
	return _c
}

// Suspend provides a mock function with given fields: ctx
func (_m *MockSupervisor) Suspend(ctx context.Context) (WaitFunc, error) {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Suspend")
	}

	var r0 WaitFunc
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) (WaitFunc, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) WaitFunc); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(WaitFunc)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockSupervisor_Suspend_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Suspend'
type MockSupervisor_Suspend_Call struct {
	*mock.Call
}

// Suspend is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockSupervisor_Expecter) Suspend(ctx interface{}) *MockSupervisor_Suspend_Call {
	return &MockSupervisor_Suspend_Call{Call: _e.mock.On("Suspend", ctx)}
}

func (_c *MockSupervisor_Suspend_Call) Run(run func(ctx context.Context)) *MockSupervisor_Suspend_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context))
	})
	return _c
}

func (_c *MockSupervisor_Suspend_Call) Return(_a0 WaitFunc, _a1 error) *MockSupervisor_Suspend_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockSupervisor_Suspend_Call) RunAndReturn(run func(context.Context) (WaitFunc, error)) *MockSupervisor_Suspend_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSupervisor creates a new instance of MockSupervisor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSupervisor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSupervisor {
	mock := &MockSupervisor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
