name: Build and Test

on:
  push:
    paths-ignore:
      - "README.md"
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.ref_name }}
      COMMIT: ${{ github.sha }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install Dependencies
        run: go mod download

      - name: Run Build
        run: make build

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: shimmy
          path: ./bin/shimmy

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version-file: ./go.mod

      - name: Install Dependencies
        run: go mod download

      - name: Run Tests
        run: go test -json ./... > TestResults.json

      - name: Upload test results
        uses: actions/upload-artifact@v4
        with:
          name: Go-results
          path: TestResults.json

  build-docker:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [build, test]
    concurrency:
      group: ${{ github.ref }}
      cancel-in-progress: ${{ github.event_name == 'pull_request' || github.ref_name != github.event.repository.default_branch }}
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up QEMU
        if: github.ref_name == github.event.repository.default_branch
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx (QEMU)
        if: github.ref_name == github.event.repository.default_branch
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=raw,value=latest,enable={{is_default_branch}}
            type=edge,branch=main
          images: |
            ghcr.io/${{ github.repository }}/shimmy

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: ${{ (github.event_name == 'push' && (github.ref_name == github.event.repository.default_branch || github.ref_type == 'tag')) || github.event_name == 'pull_request' }}
          platforms: ${{ github.ref_name == github.event.repository.default_branch && 'linux/amd64,linux/arm64' || 'linux/amd64' }}
          provenance: false
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max,ignore-error=true
          build-args: |
            VERSION=${{ github.ref_name }}
            COMMIT=${{ github.sha }}
